# Generated by Django 4.0.3 on 2023-04-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_rename_description_binvo_closet_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='name',
            new_name='href',
        ),
    ]
