# Generated by Django 4.0.3 on 2023-04-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_rename_name_binvo_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='href',
        ),
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
